// Sync the runner pricing tables from LiteLLM's community-maintained model cost
// map (model_prices_and_context_window.json). LiteLLM tracks rates across all
// providers within ~a day of model launches; we vendor a snapshot so priceUsage()
// stays synchronous + offline. Neither OpenAI nor Anthropic exposes a programmatic
// price endpoint, so this dataset is the practical source of truth.
//
// On-demand: run it to pull the latest rates when you want, no automation.
// Usage:
//   pnpm pricing:sync     # rewrite pricing.generated.ts
//   pnpm pricing:check    # report drift vs live (exit 1)
//
// After a write, format the generated file before committing.

import { writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import yargs from "yargs";
import { hideBin } from "yargs/helpers";

const LITELLM_URL =
  "https://raw.githubusercontent.com/BerriAI/litellm/main/model_prices_and_context_window.json";

// scripts/ -> package root -> src/runners/pricing.generated.ts.
const PACKAGE_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const GENERATED_FILE = path.join(PACKAGE_ROOT, "src", "runners", "pricing.generated.ts");

// Providers agent-kit prices. claude-cli reuses the anthropic table; ollama has none.
const PROVIDERS = ["anthropic", "openai"] as const;
// LiteLLM `mode` values that denote text generation our runners can drive.
const TEXT_MODES = new Set(["chat", "responses"]);

const note = (msg: string): void => console.log(`[pricing-sync] ${msg}`);
const fail = (msg: string): void => console.error(`[pricing-sync] ${msg}`);

interface ModelPrice {
  inputPerMTok: number;
  outputPerMTok: number;
  cacheReadPerMTok?: number;
  cacheWritePerMTok?: number;
}
type PriceTable = Record<string, ModelPrice>;
type Tables = { anthropic: PriceTable; openai: PriceTable };

interface LiteLlmEntry {
  litellm_provider?: string;
  mode?: string;
  input_cost_per_token?: number;
  output_cost_per_token?: number;
  cache_read_input_token_cost?: number;
  cache_creation_input_token_cost?: number;
}

// Per-token -> per-MTok, rounded to drop float noise (e.g. 1.5e-6 * 1e6 = 1.5).
const toPerMTok = (perToken: unknown): number | undefined => {
  if (typeof perToken !== "number" || !Number.isFinite(perToken)) return undefined;
  return Number((perToken * 1_000_000).toFixed(6));
};

export const buildTables = (raw: Record<string, unknown>): Tables => {
  const tables: Tables = { anthropic: {}, openai: {} };
  for (const [model, value] of Object.entries(raw)) {
    if (model === "sample_spec" || !value || typeof value !== "object") continue;
    const entry = value as LiteLlmEntry;
    const provider = entry.litellm_provider;
    if (provider !== "anthropic" && provider !== "openai") continue;
    if (!entry.mode || !TEXT_MODES.has(entry.mode)) continue;
    if (model.includes("/")) continue; // bare model IDs only; skip region/prefixed variants
    const inputPerMTok = toPerMTok(entry.input_cost_per_token);
    const outputPerMTok = toPerMTok(entry.output_cost_per_token);
    if (inputPerMTok === undefined || outputPerMTok === undefined) continue;
    const price: ModelPrice = { inputPerMTok, outputPerMTok };
    const cacheRead = toPerMTok(entry.cache_read_input_token_cost);
    const cacheWrite = toPerMTok(entry.cache_creation_input_token_cost);
    if (cacheRead !== undefined) price.cacheReadPerMTok = cacheRead;
    if (cacheWrite !== undefined) price.cacheWritePerMTok = cacheWrite;
    tables[provider][model] = price;
  }
  return tables;
};

const fetchRaw = async (): Promise<Record<string, unknown>> => {
  const res = await fetch(LITELLM_URL);
  if (!res.ok) throw new Error(`GET ${LITELLM_URL} -> ${res.status} ${res.statusText}`);
  return (await res.json()) as Record<string, unknown>;
};

const renderTable = (name: string, table: PriceTable): string => {
  const rows = Object.keys(table)
    .sort()
    .map((key) => {
      const p = table[key]!;
      const parts = [`inputPerMTok: ${p.inputPerMTok}`, `outputPerMTok: ${p.outputPerMTok}`];
      if (p.cacheReadPerMTok !== undefined) parts.push(`cacheReadPerMTok: ${p.cacheReadPerMTok}`);
      if (p.cacheWritePerMTok !== undefined)
        parts.push(`cacheWritePerMTok: ${p.cacheWritePerMTok}`);
      return `  ${JSON.stringify(key)}: { ${parts.join(", ")} },`;
    });
  return `export const ${name}: Record<string, ModelPrice> = {\n${rows.join("\n")}\n};`;
};

const renderFile = (tables: Tables): string =>
  `// GENERATED by scripts/pricing-sync.ts -- DO NOT EDIT BY HAND.
// Source: ${LITELLM_URL}
// Regenerate: pnpm pricing:sync (then format before committing).
import type { ModelPrice } from "./pricing.js";

${renderTable("ANTHROPIC_PRICES", tables.anthropic)}

${renderTable("OPENAI_PRICES", tables.openai)}
`;

const loadCommitted = async (): Promise<Tables> => {
  const mod = (await import(pathToFileURL(GENERATED_FILE).href)) as {
    ANTHROPIC_PRICES: PriceTable;
    OPENAI_PRICES: PriceTable;
  };
  return { anthropic: mod.ANTHROPIC_PRICES, openai: mod.OPENAI_PRICES };
};

// Returns human-readable drift lines (empty = in sync).
export const diffTables = (live: Tables, committed: Tables): string[] => {
  const lines: string[] = [];
  for (const provider of PROVIDERS) {
    const l = live[provider];
    const c = committed[provider];
    for (const model of Object.keys({ ...l, ...c }).sort()) {
      const a = l[model];
      const b = c[model];
      if (a && !b) lines.push(`+ ${provider}/${model} (new upstream)`);
      else if (!a && b) lines.push(`- ${provider}/${model} (removed upstream)`);
      else if (a && b && JSON.stringify(a) !== JSON.stringify(b)) {
        lines.push(`~ ${provider}/${model}: ${JSON.stringify(b)} -> ${JSON.stringify(a)}`);
      }
    }
  }
  return lines;
};

const runSync = async (): Promise<void> => {
  const tables = buildTables(await fetchRaw());
  writeFileSync(GENERATED_FILE, renderFile(tables));
  const n = Object.keys(tables.anthropic).length + Object.keys(tables.openai).length;
  note(`Wrote ${path.relative(PACKAGE_ROOT, GENERATED_FILE)} (${n} models)`);
  note("Format the generated file before committing.");
};

const runCheck = async (): Promise<void> => {
  const [live, committed] = await Promise.all([fetchRaw().then(buildTables), loadCommitted()]);
  const drift = diffTables(live, committed);
  if (drift.length === 0) {
    note("Pricing snapshot is in sync with LiteLLM.");
    return;
  }
  fail(`Pricing snapshot drifted from LiteLLM (${drift.length} change(s)):`);
  for (const line of drift) console.log(`  ${line}`);
  fail("Run `pnpm pricing:sync` to refresh.");
  process.exit(1);
};

const runCli = (): void => {
  const argv = yargs(hideBin(process.argv))
    .option("check", {
      type: "boolean",
      default: false,
      describe: "Fail if the committed table drifts from live LiteLLM data (no write)",
    })
    .strict()
    .help()
    .parseSync() as { check: boolean };

  (argv.check ? runCheck() : runSync()).catch((err: unknown) => {
    fail(err instanceof Error ? err.message : String(err));
    process.exit(1);
  });
};

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  runCli();
}
